version: "3.1"

services:
  mariadb:
    image: mariadb
    restart: always
    ports:
      - 8081:3306
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_USER: kasun
      MARIADB_PASSWORD: 1234
    volumes:
      - ./../../DB/maria_volume:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8082:80
    environment:
      - PMA_ARBITRARY=1

volumes:
  maria_volume:
